---
name: Continuous Integration (CI)

on: [push, pull_request]

jobs:
  test:
    name: Run all tests
    runs-on: ubuntu-22.04
    env:
      # Based on the Maven CI/CD template from GitLab:
      # https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Maven.gitlab-ci.yml
      # It is recommended to use these variables to reduce noise in the job logs
      MAVEN_OPTS: >
        -Dhttps.protocols=TLSv1.2
        -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
        -Dorg.slf4j.simpleLogger.showDateTime=true
        -Djava.awt.headless=true
      MAVEN_CLI_OPTS: >
        --batch-mode
        --errors
        --fail-at-end
        --show-version
        -DinstallAtEnd=true
        -DdeployAtEnd=true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"
      - name: Install Firefox ESR
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: "latest-esr"
      - name: Run unit tests
        run: mvn $MAVEN_CLI_OPTS test -Dgroups=unit -Djacoco.destFile=target/jacoco-unit.exec
      - name: Run functional tests
        run: |
          mvn $MAVEN_CLI_OPTS test -Dgroups=e2e -Djacoco.destFile=target/jacoco-functional.exec
      - name: Merge code coverage reports
        run: |
          mvn verify -DskipTests
      - name: Run SonarScanner
        run: |
          mvn -B verify -DskipTests org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
